<a href="https://colab.research.google.com/github/shelvasha/Notebooks/blob/main/00_Tensorflow_Fundementals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intro & Fundementals to TensorFlow

This is the intro covering the basics of tensors using Tensorflow.

More specifically, we're going to cover:

* Introduction to tensors
* Retrieving information from tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tf functions
* Using GPUS
* Exercises



### Scalars, Vectors & Tensors

#### Overview & Definitions

* Scalar: A single number
* Vector: a number with direction.
* Matrix: a 2-dimensional array of numbers
* Tensor: a n-dimensional array of numbers.

In [ ]:
# Import Tensorflow

import tensorflow as tf
print (tf.__version__) # Checks which version of tensorflow currently being used.

2.4.1


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor (ndim stands for the number of dimensions)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check dimension of vector
vector.ndim

1

In [ ]:
# Create a matrix (has more than one dimension)
matrix = tf.constant([[10,14],[8,7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 14],
       [ 8,  7]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix
another_matrix = tf.constant([[10.,14.],[8.,7.],[5.,30.]], dtype=tf.float16) # Specifies the data type of the matrix
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10., 14.],
       [ 8.,  7.],
       [ 5., 30.]], dtype=float16)>

In [ ]:
another_matrix.ndim # It's 2. Why?

2

In [ ]:
# Creating a Tensor
tensor = tf.constant([[[1,2,3],[4,5,6]],
                      [[7,8,9],[10,11,12]],
                      [[13,14,15],[16,17,18]],])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim # It's 3

3

### Creating a `tf.Variable`

In [ ]:
changeable_tensor = tf.Variable([10,14])
unchangeable_tensor = tf.constant([10,14])
changeable_tensor,unchangeable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 14], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 14], dtype=int32)>)

In [ ]:
# Let's try changing elements in our changeable tensor
changeable_tensor[0] = 7

TypeError: ignored

In [ ]:
# Spoiler, the first doesn't work. There's an assign method.
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 14], dtype=int32)>

In [ ]:
# Doing the same for `unchangeable_tensor` doesn't work for either assignment.
# This is because .constant() means that the tensor once created in immutable, meaning it can't be changed.


Note: It's rare to need to decide whether or not your tensors are immutable or mutable, TensorFlow will do this for you.

### Creating Random Tensors
* Random tensors are of some arbitrary size and contain random numbers.
* Technically, random tensors are already implemented in when we have data input.

In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_1

random_2 = tf.random.Generator.from_seed(15)
random_2 = random_2.normal(shape=(3,2))
random_2


# Are they equal?
random_1, random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.33149973, -0.5445254 ],
        [ 1.5222508 ,  0.59303206],
        [-0.63509274,  0.3703566 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

### Shuffling elements within a tensor
* The whole point of shuffling is to ensure that your model, when TensorFlow is tweaking its values, doesn't skew towards one specific type of data. It'll make more sense in practice.

In [ ]:
# Shuffling a tensor
not_shuffled = tf.constant([[10,7],[3,4],[2,5]])
not_shuffled.ndim

# Shuffle the non-shuffled tensor
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

**Excercises**

In [ ]:
not_shuffled_1 = tf.constant([[1,7],[3,21],[2,3]])
not_shuffled_2 = tf.constant([[17,1],[3,5],[2,5]])
not_shuffled_3 = tf.constant([[90,7],[3,4],[2,8]])
not_shuffled_4 = tf.constant([[21,8],[3,78],[2,2]])
not_shuffled_5 = tf.constant([[4,5],[3,90],[2,1]])


tf.random.shuffle(not_shuffled_1, seed=2)
tf.random.shuffle(not_shuffled_2, seed=7)
tf.random.shuffle(not_shuffled_3, seed=52)
tf.random.shuffle(not_shuffled_4, seed=10)
tf.random.shuffle(not_shuffled_5, seed=4)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3, 90],
       [ 2,  1],
       [ 4,  5]], dtype=int32)>

✅ **Takeaway**:

If you want the shuffled tensors to be shuffled the same way, the global shuffle `tf.random.set)seed(x)` will ensure reproducibility.

### Other ways to make tensors

In [ ]:
# From NumPy: .ones()- creates an array filled with ones.
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Create an array filled with zeros.
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
# You can also turn NumPy arrays into tensors
import numpy as np

numpy_A = np.arange(1,25, dtype=np.int32) # Creates a NumPy array between 1:25.
numpy_A

# X = tf.constant(some_matrix) # Capital for matrix
# y = tf.constant(vector) # lowercase for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

The main difference betweeb NumPy arrays and Tensorflow is that the tensors can be run on a GPU.

In [ ]:
A = tf.constant(numpy_A, shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
# Creating a random array in NumPy
numpy_B = np.random.rand(1,25)
tf.constant(numpy_B, shape=(5,5,1))


<tf.Tensor: shape=(5, 5, 1), dtype=float64, numpy=
array([[[0.68958143],
        [0.6785252 ],
        [0.68011063],
        [0.75386639],
        [0.26046596]],

       [[0.81437099],
        [0.06954139],
        [0.47054294],
        [0.75027556],
        [0.64069035]],

       [[0.14150282],
        [0.55692655],
        [0.34664578],
        [0.65381203],
        [0.6730201 ]],

       [[0.28779618],
        [0.47219626],
        [0.65008114],
        [0.04970666],
        [0.10423215]],

       [[0.87909588],
        [0.08437172],
        [0.56982459],
        [0.8723653 ],
        [0.25040608]]])>

### Getting Information from Tensors

When dealing with tensors, you wan to be aware of the following attributes:

* Shape
* Rank
* Axis or Dimension
* Size

In [ ]:
# Create a fank 4 tensor (4 dimension tensor)
rank_4 = tf.zeros(shape=(2,3,4,5))
rank_4[0]
rank_4.shape, rank_4.ndim, tf.size(rank_4)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get various attributes of our tensor
print("Data type of every element:", rank_4.dtype)
print("Number of dimensions (rank):", rank_4.ndim)
print("Shape of tensor:", rank_4.shape)
print("Elements on 0 axis:", rank_4.shape[0])
print("Elements on last axis:", rank_4.shape[-1])
print("Total elements tensor:", tf.size(rank_4))
print("Total elements tensor:", tf.size(rank_4).numpy())

Data type of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements on 0 axis: 2
Elements on last axis: 5
Total elements tensor: tf.Tensor(120, shape=(), dtype=int32)
Total elements tensor: 120


### Indexing Tensors
- Tensors can be indexed just like Python lists.

In [ ]:
# Get the first 2 elements of each dimension
rank_4[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor
rank_2 = tf.constant([[1,2],[3,4]])

# Get shape and dimensions 
rank_2.shape, rank_2.ndim


# Get last items of tensor
rank_2[:,-2]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>

### Adding another dimension to a tensor


In [ ]:
rank_3 = rank_2[...,tf.newaxis]
rank_3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
# Alternative to .newaxis
tf.expand_dims(rank_2, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

### Manipulating Tensors

In [ ]:
# You can add or subtract values to a tensor by using the basic python operators

tensor = tf.constant([[1,2],[3,4]])
tensor + 10

tensor = tf.constant([[1,2],[3,4]])
tensor - 10

# Multiplication also works
tensor = tf.constant([[1,2],[3,4]])
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [ ]:
# We can use the TensorFlow built-in functions as well `tf.multiplY(tensor,value you wantto multiply to the tensor)`

## Matrix Multiplication
* Perhaps one of the most important operations performed in machine learning.

* To review how matrix multiplication works: [Link - Math is Fun]('https://www.mathsisfun.com/algebra/matrix-multiplying.html')

* There are two rules to Matrix multiplication
  1. The inner dimension has to be the same dimensions as the inner diminson.
  2. The resulting matrix has the same shape as the inner dimensions.




In [ ]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [ ]:
# Example Tensor Multiuplication
tensor_A = tf.constant([[1,2,5],[7,2,1],[3,3,3]])
tensor_B = tf.constant([[3,5],[6,7],[1,8]])

tf.matmul(tensor_A, tensor_B)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
# Transforming Matrices/Tensors

# .reshape()
tf.reshape(tensor_A, shape=(3,3))

# .transpose()
tf.transpose(tensor_B)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 6, 1],
       [5, 7, 8]], dtype=int32)>

### 🔁 Review: The dot product
- also referred to a matrix multiplication
- You can perform using
  - `tf.matmul()`
  - `tf.tensordot()`

In [ ]:
# Perform the dot product on tensor_A and tensor_B
# tensor_A,tensor_B

tf.tensordot(tf.transpose(tensor_B), tensor_A, axes=1) # axes

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[48, 21, 24],
       [78, 48, 56]], dtype=int32)>

In [ ]:
tf.tensordot(tf.reshape(tensor_B, (2,3)),tensor_A, axes=1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[56, 34, 38],
       [38, 40, 60]], dtype=int32)>

#### 💡 When multiplying matrices, .shape() and .transpose() are not the same.

In [ ]:
print("Original tensor", tensor_B)
print("\n")

print("Original tensor", tf.reshape(tensor_B, (2,3)))
print("\n")

print("Original tensor", tf.transpose(tensor_B))
print("\n")


Original tensor tf.Tensor(
[[3 5]
 [6 7]
 [1 8]], shape=(3, 2), dtype=int32)


Original tensor tf.Tensor(
[[3 5 6]
 [7 1 8]], shape=(2, 3), dtype=int32)


Original tensor tf.Tensor(
[[3 6 1]
 [5 7 8]], shape=(2, 3), dtype=int32)




### Aggregating Tensors
- Aggregating tensors is equivalent to condensing them from multiple values into a smaller number of values.

In [ ]:
E = tf.constant(np.random.randint(0,100, size=20))
print(E)
print(tf.reduce_min(E)) # Minimum of the tensor
print(tf.reduce_max(E)) # Maximum of the tensor
print(tf.reduce_mean(E)) # Mean of the tensor
print(tf.reduce_sum(E)) # Sum of the tensor


# Bonus
print(tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))) # Variance of the tensor
print(tf.math.reduce_std(tf.cast(E,dtype=tf.float32))) # Standard deviation of the tensor


tf.Tensor([ 3 92 11 66 94 28 39 61 96 36 10 84 32 54 23 42 88  8 68 77], shape=(20,), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(96, shape=(), dtype=int64)
tf.Tensor(50, shape=(), dtype=int64)
tf.Tensor(1012, shape=(), dtype=int64)
tf.Tensor(943.34, shape=(), dtype=float32)
tf.Tensor(30.71384, shape=(), dtype=float32)


### Finding Positional maximums and minimums of a tensor

In [ ]:
tf.random.set_seed(14)
F = tf.random.uniform(shape=[30])
# print(F)

# Index of our largest value position (Where in the matrix is the max value?)
print("Index of largest value position: ",tf.argmax(F).numpy())

# Index of our largest value position (Where in the matrix is the max value?)
print("Largest value of F: ",tf.reduce_max(F).numpy())

# Checking for Equality
F[tf.argmax(F)] == tf.reduce_max(F)



Index of largest value position:  26
Largest value of F:  0.9998363


<tf.Tensor: shape=(), dtype=bool, numpy=True>

### Squeezing Tensors (removing all single dimensions)

In [ ]:
# Create a tensor to start out
tf.random.set_seed(42)
S = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))

print(S)

print(tf.squeeze(S))


tf.Tensor(
[[[[[0.6645621  0.44100678 0.3528825  0.46448255 0.03366041 0.68467236
     0.74011743 0.8724445  0.22632635 0.22319686 0.3103881  0.7223358
     0.13318717 0.5480639  0.5746088  0.8996835  0.00946367 0.5212307
     0.6345445  0.1993283  0.72942245 0.54583454 0.10756552 0.6767061
     0.6602763  0.33695042 0.60141766 0.21062577 0.8527372  0.44062173
     0.9485276  0.23752594 0.81179297 0.5263394  0.494308   0.21612847
     0.8457197  0.8718841  0.3083862  0.6868038  0.23764038 0.7817228
     0.9671384  0.06870162 0.79873943 0.66028714 0.5871513  0.16461694
     0.7381023  0.32054043]]]]], shape=(1, 1, 1, 1, 50), dtype=float32)
tf.Tensor(
[0.6645621  0.44100678 0.3528825  0.46448255 0.03366041 0.68467236
 0.74011743 0.8724445  0.22632635 0.22319686 0.3103881  0.7223358
 0.13318717 0.5480639  0.5746088  0.8996835  0.00946367 0.5212307
 0.6345445  0.1993283  0.72942245 0.54583454 0.10756552 0.6767061
 0.6602763  0.33695042 0.60141766 0.21062577 0.8527372  0.44062173
 0.9485276

### One-Hot Encoding

* A form of numerical encoding

In [ ]:
# Create a list of indices

some_list = [0,1,2,3]
tf.one_hot(some_list, 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

### Tensors & NumPy
* Tensorflow and Numpy work very well together.

In [ ]:
# Create a tensor from a NumPy array
J = tf.constant(np.array([3,4,5,6]))
J

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([3, 4, 5, 6])>

In [ ]:
# Convert Tensor into NumPy array
np.array(J), type(np.array(J))

(array([3, 4, 5, 6]), numpy.ndarray)

In [ ]:
# Convert tensor J into a NumPy array

J.numpy(), type(J.numpy())

(array([3, 4, 5, 6]), numpy.ndarray)